import { defineConfig } from 'eslint/config';
import webgrip from '@webgrip/eslint-config-astro';

export default defineConfig([
  ...webgrip,
  {
    files: ['scripts/export-banners.mjs'],
    languageOptions: { globals: { document: 'readonly', RELEASE: 'readonly' } },
  },
  {
    files: ['docs/brand/templates/**/*.js'],
    languageOptions: { globals: { window: 'readonly' } },
  },
  {
    files: ['ops/dns/**/*.js'],
    languageOptions: {
      globals: Object.fromEntries(
        [
          'A',
          'AAAA',
          'ALIAS',
          'CAA',
          'CNAME',
          'DS',
          'HTTPS',
          'LOC',
          'MX',
          'NAPTR',
          'NS',
          'PTR',
          'SOA',
          'SRV',
          'SSHFP',
          'SVCB',
          'TLSA',
          'TXT',
          'D',
          'DEFAULTS',
          'D_EXTEND',
          'DefaultTTL',
          'DnsProvider',
          'IGNORE',
          'IGNORE_NAME',
          'IGNORE_TARGET',
          'NAMESERVER',
          'NAMESERVER_TTL',
          'NewDnsProvider',
          'NewRegistrar',
          'REV',
          'TTL',
          'CF_PROXY_DEFAULT',
          'CF_PROXY_FULL',
          'CF_PROXY_OFF',
          'CF_PROXY_ON',
          'CF_REDIRECT',
          'CF_SINGLE_REDIRECT',
          'CF_TEMP_REDIRECT',
          'CF_WORKER_ROUTE',
        ].map((name) => [name, 'readonly']),
      ),
    },
  },
  {
    files: ['.releaserc.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { require: 'readonly', module: 'writable' },
    },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
]);
