name = "twente-dev"
compatibility_date = "2026-08-01"
workers_dev = false

routes = [{ pattern = "twente.dev/*", zone_name = "twente.dev" }]

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true

