name: "[Scheduled] DNS Drift"

on:
  schedule:
    - cron: "45 5 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dns-drift:
    name: "DNS Drift"
    uses: webgrip/workflows/.forgejo/workflows/dnscontrol.yml@5a0972c30ef4b2281bb79c61887410a8c3ccc2b6 # v2.6.2
    with:
      mode: drift
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_DNS_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
