/**
 * Derive the nginx preview-container config from the Cloudflare deploy contract,
 * so the two can no longer drift apart by hand.
 *
 * Why this exists: ops/docker/web mirrored public/_redirects and public/_headers
 * manually, guarded only by "Change one, change both" comments — a contract that
 * held exactly until someone forgot (three near-misses in the 2026-09-03 parity
 * round alone). The parity container is only useful if its behaviour matches
 * Cloudflare's, and behaviour that must match should be derived, not copied.
 *
 * What it does:
 *   1. GENERATES ops/docker/web/security-headers.conf entirely from the `/*`
 *      block of public/_headers.
 *   2. GENERATES the redirect `location` blocks in ops/docker/web/nginx.conf
 *      from public/_redirects, splicing only the marked region — everything
 *      else in nginx.conf stays hand-written.
 *   3. VERIFIES the cache tiers: every path rule in public/_headers that sets
 *      Cache-Control must be served by an nginx location carrying the same
 *      value. Verified rather than generated because those locations carry
 *      nginx-specific extras (`default_type text/calendar`, `try_files`) that
 *      are not mechanical.
 *
 * Modes: `pnpm gen:ops` rewrites the derived files; `pnpm gen:ops --check`
 * fails (exit 1) if the files on disk differ from what would be generated —
 * that is the CI guard in the container-parity job and `just parity`.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const HEADERS_FILE = 'public/_headers';
const REDIRECTS_FILE = 'public/_redirects';
const NGINX_CONF = 'ops/docker/web/nginx.conf';
const SECURITY_CONF = 'ops/docker/web/security-headers.conf';

const BEGIN_MARK = '# BEGIN generated from public/_redirects';
const END_MARK = '# END generated from public/_redirects';

const CHECK = process.argv.includes('--check');

interface HeaderBlock {
  path: string;
  headers: Array<{ name: string; value: string }>;
}

/** Parse Cloudflare's _headers format: a path line, then indented `Name: value` lines. */
function parseHeaders(text: string): HeaderBlock[] {
  const blocks: HeaderBlock[] = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.replace(/\s+$/, '');
    if (line === '' || line.trimStart().startsWith('#')) continue;
    if (!line.startsWith(' ') && !line.startsWith('\t')) {
      blocks.push({ path: line.trim(), headers: [] });
      continue;
    }
    const m = line.trim().match(/^([A-Za-z0-9-]+):\s*(.*)$/);
    const block = blocks[blocks.length - 1];
    if (!m || !block) {
      console.error(`gen-ops: cannot parse ${HEADERS_FILE} line: ${line}`);
      process.exit(1);
    }
    block.headers.push({ name: m[1] as string, value: m[2] as string });
  }
  return blocks;
}

/** Parse Cloudflare's _redirects format: `source target status` per rule line. */
function parseRedirects(text: string): Array<{ source: string; target: string; status: string }> {
  const rules: Array<{ source: string; target: string; status: string }> = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;
    const parts = line.split(/\s+/);
    if (parts.length !== 3 || !/^\d{3}$/.test(parts[2] as string)) {
      console.error(`gen-ops: cannot parse ${REDIRECTS_FILE} rule: ${line}`);
      process.exit(1);
    }
    rules.push({
      source: parts[0] as string,
      target: parts[1] as string,
      status: parts[2] as string,
    });
  }
  return rules;
}

function generateSecurityConf(blocks: HeaderBlock[]): string {
  const root = blocks.find((b) => b.path === '/*');
  if (!root) {
    console.error(`gen-ops: no /* block in ${HEADERS_FILE}`);
    process.exit(1);
  }
  const lines = root.headers.map((h) => `add_header ${h.name} "${h.value}" always;`);
  return `# GENERATED by scripts/gen-ops.ts from the /* block of public/_headers.
# Do not edit by hand — change public/_headers and run \`pnpm gen:ops\`.
#
# This is a separate file because nginx's \`add_header\` does NOT inherit into a
# location block that declares its own — so the cache-control locations in
# nginx.conf would silently drop every security header if these were only set
# at server level. Each location includes this file explicitly.

${lines.join('\n')}
`;
}

function generateRedirectRegion(
  rules: Array<{ source: string; target: string; status: string }>,
): string {
  const blocks = rules.map(
    (r) => `    location = ${r.source} {\n        return ${r.status} ${r.target};\n    }`,
  );
  const header =
    `    ${BEGIN_MARK}\n` +
    '    # Do not edit by hand — the rationale for each rule lives as comments in\n' +
    '    # public/_redirects; change that file and run `pnpm gen:ops`.';
  return [header, ...blocks, `    ${END_MARK}`].join('\n\n');
}

function spliceNginx(conf: string, region: string): string {
  const begin = conf.indexOf(`    ${BEGIN_MARK}`);
  const endMark = `    ${END_MARK}`;
  const end = conf.indexOf(endMark);
  if (begin === -1 || end === -1 || end < begin) {
    console.error(`gen-ops: ${NGINX_CONF} is missing the ${BEGIN_MARK} / ${END_MARK} markers`);
    process.exit(1);
  }
  return conf.slice(0, begin) + region + conf.slice(end + endMark.length);
}

interface NginxLocation {
  modifier: string; // '', '=', '~'
  pattern: string;
  cacheControl: string | null;
  order: number;
}

function parseNginxLocations(conf: string): NginxLocation[] {
  const locations: NginxLocation[] = [];
  const re = /location\s+(?:(=|~\*?|\^~)\s+)?(\S+)\s*\{([^}]*)\}/g;
  let m: RegExpExecArray | null;
  let order = 0;
  while ((m = re.exec(conf)) !== null) {
    const body = m[3] ?? '';
    const cc = body.match(/add_header\s+Cache-Control\s+"([^"]*)"/);
    locations.push({
      modifier: m[1] ?? '',
      pattern: m[2] as string,
      cacheControl: cc?.[1] ?? null,
      order: order++,
    });
  }
  return locations;
}

/**
 * nginx location selection, simplified for this config (no ^~ blocks): an
 * exact match wins; otherwise regex locations are tried in file order; only
 * when none matches does the longest matching prefix serve the request.
 */
function matchLocation(locations: NginxLocation[], url: string): NginxLocation | null {
  const exact = locations.find((l) => l.modifier === '=' && l.pattern === url);
  if (exact) return exact;
  for (const l of locations) {
    if (l.modifier.startsWith('~') && new RegExp(l.pattern).test(url)) return l;
  }
  let best: NginxLocation | null = null;
  for (const l of locations) {
    if (l.modifier === '' && url.startsWith(l.pattern)) {
      if (!best || l.pattern.length > best.pattern.length) best = l;
    }
  }
  return best;
}

/** Every Cache-Control rule in _headers must be served identically by nginx. */
function verifyCacheTiers(blocks: HeaderBlock[], conf: string): string[] {
  const failures: string[] = [];
  const locations = parseNginxLocations(conf);
  for (const block of blocks) {
    if (block.path === '/*') continue;
    const cc = block.headers.find((h) => h.name.toLowerCase() === 'cache-control');
    if (!cc) continue;
    // A representative URL for the pattern: `/_astro/*` must serve like `/_astro/x`.
    const url = block.path.endsWith('*') ? `${block.path.slice(0, -1)}x` : block.path;
    const loc = matchLocation(locations, url);
    if (!loc || loc.cacheControl === null) {
      failures.push(
        `${block.path}: public/_headers sets "Cache-Control: ${cc.value}" but no nginx ` +
          `location serving ${url} sets Cache-Control at all`,
      );
    } else if (loc.cacheControl !== cc.value) {
      failures.push(
        `${block.path}: Cache-Control drifted\n` +
          `    public/_headers  ${cc.value}\n` +
          `    nginx (${loc.modifier || 'prefix'} ${loc.pattern})  ${loc.cacheControl}`,
      );
    }
  }
  return failures;
}

function emit(path: string, content: string, drift: string[]): void {
  const current = readFileSync(path, 'utf8');
  if (current === content) return;
  if (CHECK) {
    drift.push(`${path} is stale — run \`pnpm gen:ops\` and commit the result`);
  } else {
    writeFileSync(path, content);
    console.log(`gen-ops: wrote ${path}`);
  }
}

const headerBlocks = parseHeaders(readFileSync(HEADERS_FILE, 'utf8'));
const redirectRules = parseRedirects(readFileSync(REDIRECTS_FILE, 'utf8'));
const nginxBefore = readFileSync(NGINX_CONF, 'utf8');

const drift: string[] = [];
emit(SECURITY_CONF, generateSecurityConf(headerBlocks), drift);
emit(NGINX_CONF, spliceNginx(nginxBefore, generateRedirectRegion(redirectRules)), drift);

const cacheFailures = verifyCacheTiers(headerBlocks, readFileSync(NGINX_CONF, 'utf8'));

if (drift.length > 0 || cacheFailures.length > 0) {
  if (drift.length > 0) {
    console.error(`\ngen-ops: ${drift.length} derived file(s) out of date:\n`);
    for (const d of drift) console.error(`  ${d}`);
  }
  if (cacheFailures.length > 0) {
    console.error(`\ngen-ops: ${cacheFailures.length} cache-tier mismatch(es):\n`);
    for (const f of cacheFailures) console.error(`  ${f}\n`);
  }
  process.exit(1);
}

console.log(
  `gen-ops: security headers + ${redirectRules.length} redirect(s) derived, ` +
    `cache tiers verified${CHECK ? ' (check mode)' : ''}`,
);
