/**
 * Derive the nginx preview-container config from the Cloudflare deploy contract,
 * so the two can no longer drift apart by hand.
 *
 * Why this exists: ops/docker/web mirrored public/_redirects and public/_headers
 * manually, guarded only by "Change one, change both" comments — a contract that
 * held exactly until someone forgot (three near-misses in the 2026-09-03 parity
 * round alone). The parity container is only useful if its behaviour matches
 * Cloudflare's, and behaviour that must match should be derived, not copied.
 *
 * What it does:
 *   1. GENERATES ops/docker/web/security-headers.conf entirely from the `/*`
 *      block of public/_headers.
 *   2. GENERATES the redirect `location` blocks in nginx.conf from
 *      public/_redirects.
 *   3. GENERATES the cache-tier `location` blocks in nginx.conf from every
 *      Cache-Control rule in public/_headers. Both artifacts extend the same
 *      source; there is nothing left to compare. nginx's longest-prefix rule
 *      makes /pagefind/index/ beat /pagefind/ without regexes, and the one
 *      format-specific extra (.ics needs default_type text/calendar or no
 *      client will subscribe) is knowledge the generator owns.
 *
 * Only the marked regions of nginx.conf are spliced; the rest (clean-URL
 * canonicalisation, the HTML fallback, the 404 contract) stays hand-written.
 *
 * Modes: `pnpm gen:ops` rewrites the derived files; `pnpm gen:ops --check`
 * fails (exit 1) if the files on disk differ from what would be generated —
 * that is the CI guard in the container-parity job and `just parity`.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const HEADERS_FILE = 'public/_headers';
const REDIRECTS_FILE = 'public/_redirects';
const NGINX_CONF = 'ops/docker/web/nginx.conf';
const SECURITY_CONF = 'ops/docker/web/security-headers.conf';

const REDIRECTS_BEGIN = '# BEGIN generated from public/_redirects';
const REDIRECTS_END = '# END generated from public/_redirects';
const CACHE_BEGIN = '# BEGIN generated from public/_headers';
const CACHE_END = '# END generated from public/_headers';

const CHECK = process.argv.includes('--check');

interface HeaderBlock {
  path: string;
  headers: Array<{ name: string; value: string }>;
}

/** Parse Cloudflare's _headers format: a path line, then indented `Name: value` lines. */
function parseHeaders(text: string): HeaderBlock[] {
  const blocks: HeaderBlock[] = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.replace(/\s+$/, '');
    if (line === '' || line.trimStart().startsWith('#')) continue;
    if (!line.startsWith(' ') && !line.startsWith('\t')) {
      blocks.push({ path: line.trim(), headers: [] });
      continue;
    }
    const m = line.trim().match(/^([A-Za-z0-9-]+):\s*(.*)$/);
    const block = blocks[blocks.length - 1];
    if (!m || !block) {
      console.error(`gen-ops: cannot parse ${HEADERS_FILE} line: ${line}`);
      process.exit(1);
    }
    block.headers.push({ name: m[1] as string, value: m[2] as string });
  }
  return blocks;
}

/** Parse Cloudflare's _redirects format: `source target status` per rule line. */
function parseRedirects(text: string): Array<{ source: string; target: string; status: string }> {
  const rules: Array<{ source: string; target: string; status: string }> = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;
    const parts = line.split(/\s+/);
    if (parts.length !== 3 || !/^\d{3}$/.test(parts[2] as string)) {
      console.error(`gen-ops: cannot parse ${REDIRECTS_FILE} rule: ${line}`);
      process.exit(1);
    }
    rules.push({
      source: parts[0] as string,
      target: parts[1] as string,
      status: parts[2] as string,
    });
  }
  return rules;
}

function generateSecurityConf(blocks: HeaderBlock[]): string {
  const root = blocks.find((b) => b.path === '/*');
  if (!root) {
    console.error(`gen-ops: no /* block in ${HEADERS_FILE}`);
    process.exit(1);
  }
  const lines = root.headers.map((h) => `add_header ${h.name} "${h.value}" always;`);
  return `# GENERATED by scripts/gen-ops.ts from the /* block of public/_headers.
# Do not edit by hand — change public/_headers and run \`pnpm gen:ops\`.
#
# This is a separate file because nginx's \`add_header\` does NOT inherit into a
# location block that declares its own — so the cache-control locations in
# nginx.conf would silently drop every security header if these were only set
# at server level. Each location includes this file explicitly.

${lines.join('\n')}
`;
}

function generateRedirectRegion(
  rules: Array<{ source: string; target: string; status: string }>,
): string {
  const blocks = rules.map(
    (r) => `    location = ${r.source} {\n        return ${r.status} ${r.target};\n    }`,
  );
  const header =
    `    ${REDIRECTS_BEGIN}\n` +
    '    # Do not edit by hand — the rationale for each rule lives as comments in\n' +
    '    # public/_redirects; change that file and run `pnpm gen:ops`.';
  return [header, ...blocks, `    ${REDIRECTS_END}`].join('\n\n');
}

function generateCacheRegion(blocks: HeaderBlock[]): string {
  const locations: string[] = [];
  for (const block of blocks) {
    if (block.path === '/*') continue;
    const cc = block.headers.find((h) => h.name.toLowerCase() === 'cache-control');
    if (!cc) continue;
    // `/x/*` becomes a prefix location; an exact path an exact one. nginx's
    // longest-prefix rule orders overlapping tiers (/pagefind/index/ beats
    // /pagefind/) with no regexes needed.
    const selector = block.path.endsWith('*')
      ? `location ${block.path.slice(0, -1)}`
      : `location = ${block.path}`;
    const body = ['        include /etc/nginx/conf.d/security-headers.conf;'];
    if (block.path.endsWith('.ics')) {
      // .ics is absent from nginx's mime.types; a calendar served as
      // application/octet-stream will not subscribe in any client.
      body.push('        default_type text/calendar;');
    }
    body.push(`        add_header Cache-Control "${cc.value}" always;`);
    body.push('        try_files $uri =404;');
    locations.push(`    ${selector} {\n${body.join('\n')}\n    }`);
  }
  const header =
    `    ${CACHE_BEGIN}\n` +
    '    # Do not edit by hand — each tier and its rationale live as comments in\n' +
    '    # public/_headers; change that file and run `pnpm gen:ops`.';
  return [header, ...locations, `    ${CACHE_END}`].join('\n\n');
}

function splice(conf: string, beginMark: string, endMark: string, region: string): string {
  const begin = conf.indexOf(`    ${beginMark}`);
  const endWithIndent = `    ${endMark}`;
  const end = conf.indexOf(endWithIndent);
  if (begin === -1 || end === -1 || end < begin) {
    console.error(`gen-ops: ${NGINX_CONF} is missing the ${beginMark} / ${endMark} markers`);
    process.exit(1);
  }
  return conf.slice(0, begin) + region + conf.slice(end + endWithIndent.length);
}

function emit(path: string, content: string, drift: string[]): void {
  const current = readFileSync(path, 'utf8');
  if (current === content) return;
  if (CHECK) {
    drift.push(`${path} is stale — run \`pnpm gen:ops\` and commit the result`);
  } else {
    writeFileSync(path, content);
    console.log(`gen-ops: wrote ${path}`);
  }
}

const headerBlocks = parseHeaders(readFileSync(HEADERS_FILE, 'utf8'));
const redirectRules = parseRedirects(readFileSync(REDIRECTS_FILE, 'utf8'));

const drift: string[] = [];
emit(SECURITY_CONF, generateSecurityConf(headerBlocks), drift);

let nginx = readFileSync(NGINX_CONF, 'utf8');
nginx = splice(nginx, REDIRECTS_BEGIN, REDIRECTS_END, generateRedirectRegion(redirectRules));
nginx = splice(nginx, CACHE_BEGIN, CACHE_END, generateCacheRegion(headerBlocks));
emit(NGINX_CONF, nginx, drift);

if (drift.length > 0) {
  console.error(`\ngen-ops: ${drift.length} derived file(s) out of date:\n`);
  for (const d of drift) console.error(`  ${d}`);
  process.exit(1);
}

const tiers = headerBlocks.filter(
  (b) => b.path !== '/*' && b.headers.some((h) => h.name.toLowerCase() === 'cache-control'),
).length;
console.log(
  `gen-ops: security headers + ${redirectRules.length} redirect(s) + ${tiers} cache tier(s) ` +
    `derived${CHECK ? ' (check mode)' : ''}`,
);
